# установка: 
# 1) установка: pip install pre-commit(устанавливает программу для создания пре-коммитов)
# 2) в корне репы создать .pre-commit-config.yaml, это файл, показывающий программе pre-commit какие тесты применять для кода
# 3) запустить pre-commit install чтобы он создал сам непосредственно хук в текущем репозитории в файле .git/hooks/pre-commit
# 4) можно потом запустить для всех файлов сразу, чтобы применить новые правила ко всем файлам проекта pre-commit run --all-files
# использование:
# pre-commit run    запускает текущие хуки без коммита, использовать надо до коммита 
repos:
  - repo: https://github.com/psf/black # здесь может быть любой репо с тестами, даже local, что говорит о том, что проект использует тесты внутри себя
    rev: 21.9b0                        # версия для использования, чтобы на фиксированные правила ориентироваться
    hooks:
      - id: black                      # что именно запускать для тестов
        args: [--safe]                 # с какими аргументами запускать

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml

  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v2.0.1
    hooks:
      - id: docker-compose-check

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.64.0
    hooks:
      - id: infracost_breakdown #- Check terraform infrastructure cost
      - id: terraform_fmt #- Rewrites all Terraform configuration files to a canonical format.
      - id: terraform_docs #- Inserts input and output documentation into README.md (using terraform-docs).
      - id: terraform_docs_without_aggregate_type_defaults #- Inserts input and output documentation into README.md (using terraform-docs). Identical to terraform_docs.
      - id: terraform_docs_replace #- Overwrite content of README.md with terraform-docs.
      - id: terraform_validate #- Validates all Terraform configuration files.
      - id: terraform_providers_lock #- Updates provider signatures in dependency lock files.
      - id: terraform_tflint #- Validates all Terraform configuration files with TFLint.
      - id: terragrunt_fmt #- Rewrites all Terragrunt configuration files to a canonical format.
      - id: terragrunt_validate #- Validates all Terragrunt configuration files.
      - id: checkov #- Runs checkov on Terraform templates.
      - id: terrascan #- Runs terrascan on Terraform templates.