# установка: 
# 1) установка: pip install pre-commit(устанавливает программу для создания пре-коммитов)
# 2) в корне репы создать .pre-commit-config.yaml, это файл, показывающий программе pre-commit какие тесты применять для кода
# 3) запустить pre-commit install чтобы он создал сам непосредственно хук в текущем репозитории в файле .git/hooks/pre-commit
# 4) можно потом запустить для всех файлов сразу, чтобы применить новые правила ко всем файлам проекта pre-commit run --all-files
# использование:
# pre-commit run    запускает текущие хуки без коммита, использовать надо до коммита 
repos:
  - repo: https://github.com/psf/black # здесь может быть любой репо с тестами, даже local, что говорит о том, что проект использует тесты внутри себя
    rev: 21.9b0                        # версия для использования, чтобы на фиксированные правила ориентироваться
    hooks:
      - id: black                      # что именно запускать для тестов
        args: [--safe]                 # с какими аргументами запускать

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml